stages:
  data_ingestion:
    cmd: python src/CnnClasifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/CnnClasifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  
  prepare_base_model__:
    cmd: python src\CnnClasifier\pipeline\stage_02_pre_bse_mdl.py
    deps:
      - src\CnnClasifier\pipeline\stage_02_pre_bse_mdl.py
      - config\config.yaml
    params:
      - IMG_SIZE 
      - LEARNING_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
    outs:
      - artifacts\prepare_base_model
  

  training_model:
    cmd: python src\CnnClasifier\pipeline\stage_03_model_training.py
    deps: 
      - src\CnnClasifier\pipeline\stage_03_model_training.py
      - config\config.yaml
      - artifacts\data_ingestion\kidney-ct-scan-image
      - artifacts\prepare_base_model
    params:
      - IMG_SIZE 
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts\training\model.h5

  evaluation: 
    cmd: python src\CnnClasifier\pipeline\stage_04_eval.py
    deps:
      - src\CnnClasifier\pipeline\stage_04_eval.py
      - config\config.yaml
      - artifacts\data_ingestion\kidney-ct-scan-image
      - artifacts\prepare_base_model
    params:
      - IMG_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: False